"""Generate three Word documents for the ABEL methods paper."""
from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.style import WD_STYLE_TYPE
import os

OUT_DIR = r"C:\Users\jober\Desktop\ABEL realism"

# ── helpers ──────────────────────────────────────────────────────────
def _setup_styles(doc):
    """Configure document styles for a clean academic look."""
    style = doc.styles["Normal"]
    font = style.font
    font.name = "Times New Roman"
    font.size = Pt(11)
    pf = style.paragraph_format
    pf.space_after = Pt(6)
    pf.line_spacing = 1.15

    for level, size in [(1, 14), (2, 12), (3, 11)]:
        name = f"Heading {level}"
        h = doc.styles[name]
        h.font.name = "Times New Roman"
        h.font.size = Pt(size)
        h.font.bold = True
        h.font.color.rgb = RGBColor(0, 0, 0)
        h.paragraph_format.space_before = Pt(12)
        h.paragraph_format.space_after = Pt(4)

def _add_title(doc, text, subtitle=None):
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run(text)
    run.bold = True
    run.font.size = Pt(16)
    run.font.name = "Times New Roman"
    if subtitle:
        p2 = doc.add_paragraph()
        p2.alignment = WD_ALIGN_PARAGRAPH.CENTER
        r2 = p2.add_run(subtitle)
        r2.font.size = Pt(11)
        r2.font.name = "Times New Roman"
        r2.italic = True

def _para(doc, text, bold_prefix=None, style=None):
    if style:
        p = doc.add_paragraph(style=style)
    else:
        p = doc.add_paragraph()
    if bold_prefix:
        r = p.add_run(bold_prefix)
        r.bold = True
        p.add_run(text)
    else:
        p.add_run(text)
    return p

def _bullet(doc, text, bold_prefix=None):
    p = doc.add_paragraph(style="List Bullet")
    if bold_prefix:
        r = p.add_run(bold_prefix)
        r.bold = True
        p.add_run(text)
    else:
        p.add_run(text)
    return p


# =====================================================================
# DOCUMENT 1: Updated Methods Documentation
# =====================================================================
def generate_methods_doc():
    doc = Document()
    _setup_styles(doc)
    _add_title(doc, "ABEL",
               "Active-Learning-Driven Behavioral Scoring from Pose-Tracking Data\n"
               "Technical Reference and Methods Documentation")
    _para(doc, "Document generated: April 2026")
    doc.add_paragraph()

    # ── TOC ──
    doc.add_heading("Contents", level=1)
    toc_items = [
        "1  Overview and Design Philosophy",
        "2  System Architecture",
        "3  Project Structure and Data Organisation",
        "4  Data Import and Session Linking",
        "5  Pose Data Cleaning and Smoothing",
        "6  Pose Feature Extraction",
        "7  Context Feature Extraction (Optional)",
        "8  Behavior Definition",
        "9  Seed Examples",
        "10  Behavior Representation: Segment-Level Feature Vectors",
        "11  Active Learning: Closed-Loop Classifier Training",
        "    11.1  Training Pipeline",
        "    11.2  Classifier Families",
        "    11.3  Probability Calibration",
        "    11.4  Adaptive Complexity Tuning",
        "    11.5  Group-Aware Train/Validation Splitting",
        "12  Candidate Generation and Uncertainty Scoring",
        "13  Clip Extraction",
        "14  Review: Human-in-the-Loop Labeling",
        "15  Temporal Refinement: Dense Sliding-Window Inference",
        "16  Temporal Review: Bout Extraction and Threshold Tuning",
        "17  Model Evaluation Metrics",
        "18  Export",
        "19  Provenance and Reproducibility",
        "20  Software Dependencies",
        "21  Glossary",
    ]
    for item in toc_items:
        _para(doc, item)
    doc.add_paragraph()

    # ── 1. Overview ──
    doc.add_heading("1. Overview and Design Philosophy", level=1)
    _para(doc, (
        "ABEL is a desktop application for semi-automated behavioral scoring "
        "of video recordings generated by standard pose-tracking systems. It "
        "consumes DeepLabCut-format pose estimation data and corresponding video "
        "files, combining supervised machine learning with a human-in-the-loop "
        "active learning workflow to produce frame-accurate behavioral annotations. "
        "The system is built around the principle that strong behavioral classifiers "
        "emerge through iterative model refinement rather than one-shot training."
    ))
    _para(doc, (
        "ABEL is behavior-agnostic: it is designed to detect any temporally "
        "discrete behavior of interest defined by the researcher, given an "
        "operational definition, a small set of seed examples, and iterative "
        "human review. The application has been applied to assays including "
        "predator-odor exposure (TMT), open field, elevated plus maze, home-cage "
        "behavior, and fear conditioning paradigms in mice and rats."
    ))

    doc.add_heading("Key Design Principles", level=2)
    _bullet(doc, "Pose-first feature extraction: kinematic features are derived entirely "
            "from pose tracking files without video decoding, enabling rapid initial passes. "
            "Video is decoded only for clip extraction and optional context features.", "No-video-first. ")
    _bullet(doc, "All project state, model artifacts, and training snapshots are stored "
            "atomically on disk so work is not lost on unexpected exits.", "Crash-resilient persistence. ")
    _bullet(doc, "Every optional dependency (GPU, CUDA, UMAP, LightGBM) has a CPU "
            "fallback so the full pipeline runs on standard hardware.", "Graceful degradation. ")
    _bullet(doc, "UI tabs communicate with independent services; all computation logic "
            "resides outside the UI layer for testability and reproducibility.", "Modular service layer. ")
    _bullet(doc, "Every derived artifact records the config hash, model version, feature "
            "version, and timestamp that produced it.", "Provenance tracking. ")

    # ── 2. System Architecture ──
    doc.add_heading("2. System Architecture", level=1)
    _para(doc, (
        "ABEL is structured in six horizontal layers: the PySide6 graphical "
        "user interface (UI); a service layer containing all computational logic; "
        "a storage layer for atomic read/write of project state; a models layer "
        "with Pydantic schemas for type-safe configuration and validation; a "
        "workers layer managing background threads for long-running tasks; and "
        "an adapters placeholder for future external-backend integrations."
    ))
    _para(doc, "The overall data flow through the pipeline is as follows:")
    steps = [
        "Data Import \u2192 link video + pose files into sessions",
        "Behavior Definitions \u2192 define target behaviors with operational criteria",
        "Seed Examples \u2192 annotate confirmed positive and negative frame ranges per behavior",
        "Pose Feature Extraction \u2192 compute kinematic windows from pose CSV/H5 files",
        "Context Feature Extraction (optional) \u2192 compute video-derived features (optical flow, local motion, spatial context)",
        "Behavior Representation \u2192 build normalized segment-level feature vectors",
        "Active Learning Training \u2192 train classifier, calibrate probabilities, score uncertainty",
        "Candidate Generation \u2192 rank segments by uncertainty and competitive scoring",
        "Clip Extraction \u2192 decode video only for top-ranked candidate segments",
        "Review \u2192 present clips to researcher; accept / reject / relabel / ambiguous",
        "[ Repeat Active Learning + Review until metrics converge ]",
        "Temporal Refinement \u2192 dense sliding-window inference across full recordings",
        "Temporal Review \u2192 threshold tuning, bout extraction, false-positive feedback",
        "Export \u2192 CSV / Word DOCX / Parquet / SimBA-format outputs",
    ]
    for i, step in enumerate(steps, 1):
        _para(doc, f"{i}.  {step}")

    # ── 3. Project Structure ──
    doc.add_heading("3. Project Structure and Data Organisation", level=1)
    _para(doc, (
        "Each ABEL project is a directory tree. On creation, the following "
        "subdirectories are created automatically: config/ (YAML/JSON settings), "
        "raw/videos/ and raw/pose/ (source files), derived/ (all computed artifacts "
        "including features, models, clips, representations, and caches), "
        "exports/ (output files), logs/ (timestamped logs), temp/ (scratch space), "
        "and backups/ (periodic state snapshots)."
    ))
    _para(doc, (
        "Project configuration is split into a ProjectConfig (YAML) for "
        "user-editable experiment parameters and a ProjectState (JSON) for "
        "runtime state such as the active tab and review progress. Both use "
        "Pydantic models for validation."
    ))

    # ── 4. Data Import ──
    doc.add_heading("4. Data Import and Session Linking", level=1)
    _para(doc, (
        "The Data Import tab ingests video files (MP4, AVI, MOV, MKV) and their "
        "corresponding pose-tracking CSV or H5 files exported from DeepLabCut. "
        "The importer automatically pairs video and pose files by matching "
        "filenames using a configurable regular expression (default: the leading "
        "alphabetic + numeric prefix, e.g., 'TMT2' from 'TMT2DLC_...'). Manual "
        "subject and session assignment is also supported."
    ))
    doc.add_heading("Supported Pose Formats", level=2)
    _bullet(doc, "DeepLabCut CSV export: three header rows encoding scorer name, "
            "body-part names, and x/y/likelihood coordinates for each frame. Columns "
            "are structured as a MultiIndex: (scorer, bodypart, coordinate).")
    _bullet(doc, "DeepLabCut H5 export: equivalent hierarchical DataFrame stored "
            "under the 'df_with_missing' key (with fallback to root DataFrame).")
    _para(doc, (
        "The PoseProcessingService normalizes both formats into an internal "
        "PoseData representation containing per-body-part x, y, and likelihood "
        "arrays indexed by frame number. Body-part names are canonicalized to "
        "lowercase_underscore format (e.g., 'LeftEar' \u2192 'left_ear', "
        "'spine1' \u2192 'spine_1') using a greedy token-matching algorithm "
        "from a known anatomical vocabulary."
    ))
    doc.add_heading("Session Registry", level=2)
    _para(doc, (
        "A persistent session_registry.json tracks every import event: video and "
        "pose filenames, subject identifier, pixel scale (px/mm if provided), "
        "and first/last-seen timestamps. This enables traceability from any "
        "downstream artifact back to its source files."
    ))
    doc.add_heading("Pixel Scale Calibration", level=2)
    _para(doc, (
        "An optional per-session pixels/mm scaling factor can be entered "
        "during import. When provided, all distance-based kinematic features "
        "(displacement, speed) are converted to physical units (mm, mm/s). "
        "Without calibration, features remain in pixel units."
    ))

    # ── 5. Pose Cleaning ──
    doc.add_heading("5. Pose Data Cleaning and Smoothing", level=1)
    _para(doc, (
        "Before any kinematic features are computed, each pose file is cleaned "
        "in the following steps. All parameters are configurable via "
        "PoseSmoothingSettings in the project configuration."
    ))
    doc.add_heading("Step 1: Likelihood Thresholding", level=2)
    _para(doc, (
        "DeepLabCut assigns a per-frame likelihood score (0\u20131) to every keypoint "
        "detection. Detections with likelihood below the configured threshold "
        "(default: 0.2) are treated as missing\u2014their x/y coordinates are set "
        "to NaN for subsequent interpolation."
    ))
    doc.add_heading("Step 2: Linear Interpolation of Dropout Gaps", level=2)
    _para(doc, (
        "Consecutive NaN frames shorter than a configurable maximum gap "
        "(default: 10 frames) are filled by linear interpolation between the "
        "nearest valid detections on either side."
    ))
    doc.add_heading("Step 3: Centered Rolling-Average Smoothing", level=2)
    _para(doc, (
        "A centered rolling mean with a configurable odd-numbered window "
        "(default: 5 frames, corresponding to ~167 ms at 30 fps) is applied to "
        "all x and y coordinate series. This attenuates high-frequency jitter "
        "from the pose estimator."
    ))
    doc.add_heading("Step 4: Remaining NaN Handling", level=2)
    _para(doc, (
        "Any remaining NaN values are first forward-filled, then back-filled, "
        "then zero-filled as a last resort. This ensures no NaN values propagate "
        "into kinematic computation."
    ))

    # ── 6. Pose Feature Extraction ──
    doc.add_heading("6. Pose Feature Extraction", level=1)
    _para(doc, (
        "The Pose Features service computes kinematic feature vectors from "
        "cleaned pose data across sliding windows of the full recording, "
        "without decoding any video."
    ))
    doc.add_heading("Sliding Window Parameterization", level=2)
    _para(doc, (
        "The recording is segmented into overlapping windows defined by: "
        "window duration (default: 2.0 s at 30 fps = 60 frames) and window "
        "stride (default: 1.0 s = 30 frames). Built-in presets include "
        "Standard (2 s / 1 s stride), Short Window (1 s / 0.5 s), Long Window "
        "(4 s / 2 s), and High-Res (1 s / 0.25 s). Custom presets can be "
        "saved to config/pose_features.yaml."
    ))
    doc.add_heading("Feature Vector Layout", level=2)
    _para(doc, (
        "For each window, a nine-dimensional feature vector is computed from "
        "the body centroid trajectory and body-axis orientation:"
    ))
    _bullet(doc, "Mean speed, standard deviation of speed, maximum speed (mm/s when "
            "px/mm available; otherwise pixels/frame)", "Speed (3 features): ")
    _bullet(doc, "Mean displacement, standard deviation of displacement",
            "Displacement (2 features): ")
    _bullet(doc, "cos(mean angle), sin(mean angle), standard deviation of angle. "
            "The body-axis angle is derived from the first principal axis of the "
            "keypoint cloud (proximal \u2192 distal).", "Body-axis angle (3 features): ")
    _bullet(doc, "Mean per-frame likelihood across all tracked keypoints",
            "Pose confidence (1 feature): ")
    _para(doc, (
        "The body centroid is computed as the mean of all tracked keypoints "
        "with likelihood above the cleaning threshold."
    ))
    _para(doc, (
        "Output: derived/pose_features/{session_id}.npz \u2014 a compressed "
        "archive containing the feature matrix (n_windows \u00d7 9), window "
        "frame start/end indices, feature names, and body-part names."
    ))

    # ── 7. Context Features ──
    doc.add_heading("7. Context Feature Extraction (Optional)", level=1)
    _para(doc, (
        "The Context Feature service opens the raw video to compute per-frame "
        "environment-interaction features that complement pose kinematics. "
        "These features capture local motion dynamics, scene context, and "
        "spatial relationships to experimenter-defined regions of interest."
    ))
    doc.add_heading("Optical Flow", level=2)
    _para(doc, (
        "Dense optical flow is computed using OpenCV's Farneb\u00e4ck algorithm "
        "between consecutive downsampled grayscale frames (pyr_scale=0.5, "
        "levels=3, winsize=15, iterations=3, poly_n=5, poly_sigma=1.2). "
        "Spatial downsampling targets a ~512-pixel long edge."
    ))
    _para(doc, (
        "GPU acceleration is supported via two backends: OpenCV CUDA Farneb\u00e4ck "
        "(when available) or a PyTorch pyramidal Lucas-Kanade implementation. "
        "Adaptive GPU batch sizing scales with available VRAM, and a threading "
        "lock serializes GPU calls to prevent CUDA contention."
    ))
    doc.add_heading("Local Surface Motion (MOG2)", level=2)
    _para(doc, (
        "A Mixture of Gaussians (MOG2) background subtractor is maintained "
        "per video chunk with a 50-frame warm-up pass. Entropy-weighted motion "
        "is computed per local radius around each keypoint."
    ))
    doc.add_heading("Spatial Context Features", level=2)
    _para(doc, (
        "When ROIs are defined (target zone, subject crop), spatial features "
        "include keypoint-to-ROI distances (nose, paw, centroid) and angles "
        "to the target zone."
    ))
    doc.add_heading("Keypoint Role Mapping", level=2)
    _para(doc, (
        "Context features are conditioned on specific anatomical roles "
        "(nose, left forepaw, right forepaw). The service resolves these "
        "from actual DLC keypoint names by tokenizing each body-part name "
        "and matching against a canonical vocabulary."
    ))
    doc.add_heading("Parallel Processing", level=2)
    _para(doc, (
        "Long recordings are split into chunks of ~2000 frames and processed "
        "in parallel using a ThreadPoolExecutor. Each chunk opens its own "
        "VideoCapture handle. Optical-flow continuity across chunk boundaries "
        "is maintained by replaying the last frame of the preceding chunk."
    ))
    _para(doc, "Output: per-session parquet files in derived/context_features/sessions/.")

    # ── 8. Behavior Definition ──
    doc.add_heading("8. Behavior Definition", level=1)
    _para(doc, (
        "The Behavior tab manages user-defined behavior definitions stored "
        "in config/behavior_definitions.yaml. Each behavior records: "
        "a display name, an operational definition, inclusion/exclusion "
        "criteria, minimum duration, a color, a keyboard shortcut, and "
        "a review priority."
    ))
    _para(doc, (
        "Template vocabularies are provided for common assays: "
        "Rodent Basic (4 behaviors), Open Field Extended (6 behaviors), "
        "and EPM (3 behaviors). A system behavior 'No Behavior' is "
        "auto-created and serves as the default negative class."
    ))

    # ── 9. Seed Examples ──
    doc.add_heading("9. Seed Examples", level=1)
    _para(doc, (
        "The Seed Examples tab collects frame-range annotations to bootstrap "
        "the initial training set. Each seed example records: behavior_id, "
        "session_id, start_frame, end_frame, label_type (positive or negative), "
        "and an optional quality flag."
    ))
    _para(doc, (
        "Researchers typically provide 2\u201310 confirmed positive examples per "
        "behavior. Negative examples from non-target behaviors or clearly "
        "non-behavioral segments are also encouraged to define decision "
        "boundaries."
    ))

    # ── 10. Behavior Representation ──
    doc.add_heading("10. Behavior Representation: Segment-Level Feature Vectors", level=1)
    _para(doc, (
        "The BehaviorRepresentationService merges pose and context features "
        "into a unified representation, then normalizes and aggregates into "
        "segment-level vectors for classifier training."
    ))
    doc.add_heading("Normalization", level=2)
    _para(doc, (
        "Features are z-scored per (animal_id, session_id) group to remove "
        "between-subject and between-session confounds. This ensures that "
        "a classifier trained on one cohort can generalize to another."
    ))
    doc.add_heading("Segment Aggregation", level=2)
    _para(doc, (
        "For each base feature within a segment, eight summary statistics "
        "are computed: mean, standard deviation, median, maximum, 10th "
        "percentile, 90th percentile, energy (sum of squared values), and "
        "periodicity (peak of 1D FFT magnitude, detecting rhythmic patterns "
        "such as grooming cycles)."
    ))
    _para(doc, (
        "Full representation caches are stored per session in "
        "derived/representations/. Subset filtering for specific behaviors "
        "loads the full cache and partitions by label."
    ))

    # ── 11. Active Learning ──
    doc.add_heading("11. Active Learning: Closed-Loop Classifier Training", level=1)
    doc.add_heading("11.1 Training Pipeline", level=2)
    _para(doc, "The ActiveLearningTrainerService executes the following steps:")
    steps = [
        "Load the current training set (parquet with segment_id, label, animal_id, session_id, features).",
        "Apply temporal false-positive feedback: segments whose center falls within user-marked false-positive intervals are relabeled to 'no_behavior'.",
        "Expand co-occurring labels (pipe-separated) into per-behavior rows.",
        "Filter ambiguous and boundary_error labels.",
        "Remap alternate-behavior labels to 'no_behavior' (negative class).",
        "Cap samples per class for large datasets to prevent training slowdown while preserving balance.",
        "Drop zero-variance and weak features (>95% zero).",
        "Split into train/validation using GroupShuffleSplit (by session or subject, 75/25).",
        "Auto-tune model complexity if enabled (n_estimators, max_depth scaled by positive sample ratio).",
        "Train binary classifier with regularization.",
        "Calibrate probabilities via CalibratedClassifierCV (sigmoid or isotonic).",
        "Save model, metrics (precision, recall, F1, PR-AUC), confusion matrix, and PR curve.",
    ]
    for i, step in enumerate(steps, 1):
        _para(doc, f"{i}.  {step}")

    doc.add_heading("11.2 Classifier Families", level=2)
    _para(doc, "ABEL supports four classifier backends, selectable in the UI:")
    _bullet(doc, "Tree method = hist; GPU support via CUDA on Windows "
            "(auto-fallback to CPU). Regularization: reg_alpha=0.1, reg_lambda=1.0, "
            "subsample=0.8, colsample_bytree=0.8, learning_rate=0.1, "
            "n_estimators=300, max_depth=6.", "XGBoost (default): ")
    _bullet(doc, "Parallel/GPU acceleration (CUDA if available). Same "
            "regularization defaults as XGBoost.", "LightGBM: ")
    _bullet(doc, "Pure scikit-learn; CPU-only fallback. l2_regularization "
            "replaces reg_lambda; max_iter replaces n_estimators.",
            "HistGradientBoosting (sklearn): ")
    _bullet(doc, "Ensemble baseline with n_estimators=300, max_depth=6.",
            "RandomForest: ")

    doc.add_heading("11.3 Probability Calibration", level=2)
    _para(doc, (
        "After training, each classifier is wrapped in scikit-learn's "
        "CalibratedClassifierCV (cv='prefit') with either sigmoid (Platt "
        "scaling) or isotonic regression. This maps raw model scores to "
        "well-calibrated posterior probabilities—essential for meaningful "
        "uncertainty estimates and for setting thresholds in temporal "
        "refinement."
    ))

    doc.add_heading("11.4 Adaptive Complexity Tuning", level=2)
    _para(doc, (
        "When enabled, the system automatically scales tree depth and count "
        "based on the ratio of positive samples to feature dimensionality. "
        "Small positive sets (e.g., 10 positives, 500 features) use shallow "
        "trees (max_depth=3, n_estimators=100) to prevent overfitting in "
        "early active-learning rounds. Large positive sets use deeper and "
        "more numerous trees."
    ))

    doc.add_heading("11.5 Group-Aware Train/Validation Splitting", level=2)
    _para(doc, (
        "The primary split strategy is GroupShuffleSplit by session (75% train, "
        "25% validation), ensuring all frames from the same session remain on "
        "the same side of the split. An alternative subject-level split keeps "
        "all sessions from the same animal together. This prevents temporal "
        "leakage and mimics real deployment conditions (new session or new subject)."
    ))

    # ── 12. Candidate Generation ──
    doc.add_heading("12. Candidate Generation and Uncertainty Scoring", level=1)
    _para(doc, (
        "The CandidateGenerationService ranks unlabeled segments for human "
        "review using a multi-component uncertainty score."
    ))
    doc.add_heading("Uncertainty Components", level=2)
    _bullet(doc, "\u2212\u03a3 p\u00b7log(p) across class probabilities, measuring "
            "overall prediction uncertainty.", "Entropy: ")
    _bullet(doc, "Mean variance of predicted probabilities across classes "
            "in cross-validated folds.", "Ensemble variance: ")
    _bullet(doc, "k-NN mean distance (k=10) in feature space, detecting "
            "samples far from the training distribution.", "Density outlier: ")
    _bullet(doc, "|2nd-highest probability \u2212 highest probability|, "
            "inverted to uncertainty.", "Margin: ")
    _para(doc, (
        "These components are combined via configurable weights "
        "(default: entropy=0.4, variance=0.4, density=0.2, margin=0.0)."
    ))
    doc.add_heading("All-Behavior Competitive Scoring", level=2)
    _para(doc, (
        "When multiple behaviors are defined, a competitive score penalizes "
        "the target behavior's probability when other behaviors score highly "
        "for the same segment. This encourages review of ambiguous segments "
        "near decision boundaries."
    ))
    doc.add_heading("Query Strategies", level=2)
    _bullet(doc, "Select segments with highest weighted uncertainty.", "Uncertainty: ")
    _bullet(doc, "Select segments similar to known positive seeds.", "Prototype: ")
    _bullet(doc, "Select segments distant from previously reviewed data (diversity sampling).", "Novelty: ")
    _bullet(doc, "Select segments predicted at <0.25 probability (exploration).", "Low-probability: ")
    _bullet(doc, "Random selection from segments predicting absence of target.", "Random-absent: ")
    _para(doc, (
        "Overlap suppression is applied to the ranked list to ensure "
        "non-overlapping clips. Output: candidate_segments.json with "
        "segment_id, start/end frame, session_id, behavior_id, and all scores."
    ))

    # ── 13. Clip Extraction ──
    doc.add_heading("13. Clip Extraction", level=1)
    _para(doc, (
        "The ClipExtractionService decodes video only for selected candidate "
        "segments. Supported output resolutions include 224\u00d7224, 256\u00d7256, "
        "and 128\u00d7128 (grayscale), with configurable output FPS (default: 15). "
        "Adaptive cropping centers on the pose centroid with margin scaling "
        "relative to source resolution. Optional text overlay annotates "
        "segment metadata. Clips and thumbnails are stored in "
        "derived/clips/{session_id}/ alongside a manifest JSON."
    ))

    # ── 14. Review ──
    doc.add_heading("14. Review: Human-in-the-Loop Labeling", level=1)
    _para(doc, (
        "The Review tab presents extracted clips to the researcher. For each "
        "candidate, the reviewer selects one of: accept (confirm as target "
        "behavior), reject (confirm as non-target), ambiguous (uncertain; "
        "excluded from training), relabel (assign to a different behavior), "
        "skip, or bookmark for later."
    ))
    _para(doc, (
        "Decisions are persisted in derived/review_labels/ and merged into "
        "the training set parquet via merge_and_snapshot_training_set(), which "
        "deduplicates by segment_id (keeping the last occurrence) and saves "
        "a timestamped snapshot for reproducibility."
    ))
    _para(doc, (
        "After review, the researcher returns to the Active Learning tab to "
        "retrain the classifier with the expanded labeled set, then regenerates "
        "candidates. This cycle repeats until performance metrics converge."
    ))

    # ── 15. Temporal Refinement ──
    doc.add_heading("15. Temporal Refinement: Dense Sliding-Window Inference", level=1)
    _para(doc, "Once the classifier is satisfactory, temporal refinement applies it densely:")
    steps = [
        "Extract overlapping windows at high temporal resolution (default stride: 0.1 s).",
        "Score every frame using the trained classifier via sliding window.",
        "Average overlapping predictions per frame to produce a per-frame probability trace.",
        "Apply mutual inhibition: prob_i = prob_i \u2212 inhibition_weight \u00d7 max(other_behavior_probs), penalizing frames where multiple behaviors score highly.",
        "Apply probability calibration (temperature scaling).",
        "Smooth per-frame probabilities (moving average, Gaussian, or Savitzky-Golay filter; default: moving average, window=5).",
        "Threshold and extract bouts; merge nearby bouts (gap \u2264 3 frames); remove short bouts (min 6 frames).",
    ]
    for i, step in enumerate(steps, 1):
        _para(doc, f"{i}.  {step}")
    _para(doc, (
        "Output: per-behavior probability traces and bout intervals stored "
        "in derived/temporal_refinement/{behavior_id}/."
    ))

    # ── 16. Temporal Review ──
    doc.add_heading("16. Temporal Review: Bout Extraction and Threshold Tuning", level=1)
    _para(doc, (
        "The Temporal Review tab provides interactive visualization of "
        "per-frame probability traces for each behavior. The researcher can:"
    ))
    _bullet(doc, "Adjust onset and offset thresholds (default: 0.5 each).")
    _bullet(doc, "Tune minimum bout duration and maximum gap for merging.")
    _bullet(doc, "Preview bout extraction results overlaid on the probability trace.")
    _bullet(doc, "Mark frame intervals as false positives, which are fed back "
            "into the next training round (temporal false-positive feedback).")
    _para(doc, (
        "False-positive feedback intervals are stored in "
        "derived/temporal_refinement/{behavior_id}/feedback_intervals.json "
        "and consumed by the trainer on the next retraining cycle."
    ))

    # ── 17. Metrics ──
    doc.add_heading("17. Model Evaluation Metrics", level=1)
    _para(doc, "ABEL computes metrics at three levels:")
    _bullet(doc, "Precision, recall, F1, PR-AUC on individual frames.",
            "Frame-level: ")
    _bullet(doc, "Precision, recall, F1 on segment classifications.",
            "Segment-level: ")
    _bullet(doc, "Latency to first behavior, total behavior time, bout count, "
            "mean and median bout duration.", "Bout-level: ")
    _para(doc, (
        "Visualization outputs include PR curves (PNG), confusion matrices "
        "(PNG), and behavior separation plots (UMAP/PCA 2D scatter of target "
        "vs. non-target segments)."
    ))

    # ── 18. Export ──
    doc.add_heading("18. Export", level=1)
    _bullet(doc, "Candidate/behavior interval tables with session, subject, "
            "frame ranges, scores, and review decisions.", "CSV: ")
    _bullet(doc, "Per-behavior tables with frame indices as rows, "
            "subjects/sessions as columns, 0/1 presence indicators.",
            "Word DOCX: ")
    _bullet(doc, "Labeled segments or frame-level predictions.",
            "Parquet: ")
    _bullet(doc, "Bout-level or frame-level predictions compatible with the "
            "SimBA software package.", "SimBA XML: ")
    _bullet(doc, "Model metrics JSON, PR curves, confusion matrices, "
            "UMAP/PCA separation plots.", "Reports: ")

    # ── 19. Provenance ──
    doc.add_heading("19. Provenance and Reproducibility", level=1)
    _para(doc, (
        "Every artifact (model, features, candidates) is tagged with metadata: "
        "application version, Git commit hash (from .git if available), "
        "configuration hash (derived from project YAML), and ISO-format "
        "timestamp. This enables exact reproduction of historical runs and "
        "auditing of pipeline changes."
    ))
    _para(doc, (
        "Training set snapshots are timestamped and retained, allowing "
        "comparison of labeling progress across active-learning rounds."
    ))

    # ── 20. Dependencies ──
    doc.add_heading("20. Software Dependencies", level=1)
    _para(doc, (
        "Core: Python \u2265 3.9, PySide6, NumPy, pandas, scikit-learn, OpenCV. "
        "Optional (installed on demand via the Dependencies tab): XGBoost, "
        "LightGBM, PyTorch (CPU or CUDA), UMAP-learn. GPU acceleration "
        "requires CUDA-capable hardware and drivers; all features fall back "
        "to CPU when GPU is unavailable."
    ))

    # ── 21. Glossary ──
    doc.add_heading("21. Glossary", level=1)
    terms = [
        ("Session", "A single recording: one video file + one pose file for one subject."),
        ("Segment", "A temporal window of a session used as a unit for classification."),
        ("Bout", "A contiguous run of frames classified as a single behavior event after temporal refinement."),
        ("Seed example", "A researcher-annotated frame range used to bootstrap the initial classifier."),
        ("Candidate", "An unlabeled segment ranked by the active-learning system for human review."),
        ("Mutual inhibition", "Penalty applied during temporal refinement to frames where multiple behaviors score highly."),
        ("PR-AUC", "Area under the precision-recall curve; primary ranking metric for classifier quality."),
    ]
    for term, defn in terms:
        _bullet(doc, f" {defn}", bold_prefix=f"{term}:")

    # Save
    path = os.path.join(OUT_DIR, "ABEL_Methods_Documentation.docx")
    doc.save(path)
    print(f"Saved: {path}")


# =====================================================================
# DOCUMENT 2: Abstract and Introduction
# =====================================================================
def generate_abstract_intro():
    doc = Document()
    _setup_styles(doc)
    _add_title(doc, "ABEL: An Active-Learning Platform for Iterative\n"
               "Behavioral Classification from Pose-Estimation Data")
    doc.add_paragraph()

    # ─ Abstract ─
    doc.add_heading("Abstract", level=1)
    _para(doc, (
        "Detailed behavioral analysis is essential for understanding the neural "
        "substrates of adaptive and maladaptive behavior, yet manual annotation "
        "of complex behavioral repertoires remains subjective, time-intensive, "
        "and susceptible to observer drift. Recent advances in markerless pose "
        "estimation have enabled scalable pose tracking, but converting raw pose "
        "trajectories into reliable behavioral classifications still requires "
        "substantial labeled data and technical expertise. Here we present "
        "ABEL, an open-source, GUI-driven desktop application that implements "
        "a closed-loop active-learning pipeline for supervised behavioral "
        "classification from DeepLabCut pose-estimation data. ABEL is "
        "designed around the principle that strong classifiers emerge through "
        "iterative refinement: researchers provide a small number of seed "
        "examples, and the system trains gradient-boosted tree classifiers "
        "(XGBoost, LightGBM, or scikit-learn), calibrates prediction "
        "probabilities, scores segment-level uncertainty via entropy, ensemble "
        "variance, and density-outlier metrics, and ranks the most informative "
        "candidate segments for human review. After each review round, the "
        "labeled set is merged, the model is retrained, and candidates are "
        "regenerated\u2014closing the active-learning loop. For final annotation, "
        "a dense sliding-window temporal refinement stage produces frame-level "
        "probability traces with mutual inhibition across behaviors, "
        "configurable smoothing, and threshold-based bout extraction. "
        "The pipeline is species- and behavior-agnostic, requires no "
        "programming, and has been applied to fear-related behavior (TMT "
        "predator-odor exposure), open-field locomotion, elevated plus maze "
        "exploration, home-cage behavior, and fear conditioning paradigms in "
        "mice and rats. ABEL addresses a critical gap in the computational "
        "neuroethology toolkit by reducing the annotation burden for non-specialist "
        "behavioral neuroscientists while enforcing reproducible, provenance-tracked "
        "model development."
    ))

    # ─ Introduction ─
    doc.add_heading("Introduction", level=1)
    _para(doc, (
        "Behavioral neuroscience requires detailed, temporally precise "
        "descriptions of behavior (Krakauer et al., 2017), yet the study of "
        "complex behavioral repertoires in freely moving rodents is still "
        "constrained by the capacity of human observers to annotate recorded "
        "video consistently and at scale. Manual scoring is subjective, prone "
        "to observer fatigue and drift, and provides temporal resolution far "
        "below that of modern neural recording and manipulation techniques "
        "such as in vivo electrophysiology, fiber photometry, and single-cell "
        "calcium imaging (Falkner et al., 2016; Gunaydin et al., 2014). "
        "Computational neuroethology\u2014the marriage of traditional behavioral "
        "observation with computational and machine-learning methods (Anderson "
        "& Perona, 2014; Datta et al., 2019)\u2014has emerged as a promising "
        "solution, enabling automated behavioral assessments that often exceed "
        "human-level consistency (Gris et al., 2017), increase throughput "
        "(Schaefer & Claridge-Chang, 2012), and reduce anthropomorphic bias "
        "(Robie et al., 2017)."
    ))
    _para(doc, (
        "A first wave of open-source tools for markerless pose estimation\u2014"
        "including DeepLabCut (Mathis et al., 2018), SLEAP (Pereira et al., 2022), "
        "and DeepPoseKit (Graving et al., 2019)\u2014has provided researchers with "
        "accurate, body-part-level tracking data at negligible ongoing cost. "
        "Translating these pose trajectories into meaningful behavioral "
        "classifications, however, remains a distinct challenge. Existing "
        "supervised tools such as SimBA (Nilsson et al., 2020; Goodwin, "
        "Nilsson et al., 2024), MARS (Segalin et al., 2021), and JAABA "
        "(Kabra et al., 2013) have demonstrated that random-forest or "
        "gradient-boosted classifiers trained on hand-crafted kinematic "
        "features achieve high accuracy for well-defined social behaviors "
        "(Table 1). Unsupervised and self-supervised approaches\u2014including "
        "B-SOiD (Hsu & Yttri, 2021), VAME (Luxem et al., 2022), and "
        "MotionMapper (Berman et al., 2014)\u2014offer complementary, "
        "hypothesis-free behavioral decomposition but sacrifice direct "
        "alignment with ethologically defined categories."
    ))
    _para(doc, (
        "A common bottleneck across supervised methods is the cost of "
        "collecting sufficient labeled data. Training a robust classifier "
        "for a single behavior often requires tens of thousands of annotated "
        "frames, and retraining is needed whenever the recording setup, "
        "arena, or tracking model changes. Active learning\u2014a machine-learning "
        "paradigm in which the model selects the most informative samples "
        "for labeling\u2014has been recognized as a promising strategy for "
        "reducing annotation burden in this domain (Lorbach et al., 2019; "
        "Schweihoff et al., 2022), yet existing implementations typically "
        "require programming proficiency and do not provide an integrated "
        "end-to-end pipeline from pose import through temporal bout extraction."
    ))
    _para(doc, (
        "Here we present ABEL, an open-source desktop application "
        "(\u003chttps://github.com/[REPO]\u003e) that provides a complete, "
        "GUI-driven, active-learning pipeline for behavior classification "
        "from pose-estimation data. ABEL\'s workflow is organized around "
        "iterative model refinement: (i) the researcher provides a small "
        "number of seed examples annotated by frame range; (ii) the system "
        "extracts kinematic and optionally video-derived features, trains "
        "gradient-boosted classifiers, calibrates probabilities, and ranks "
        "unlabeled segments by a composite uncertainty metric; (iii) the "
        "researcher reviews the highest-uncertainty candidate clips in a "
        "built-in video interface; and (iv) the labeled set is expanded "
        "and the model retrained. This closed loop continues until "
        "performance metrics (precision, recall, F1, PR-AUC) converge, at "
        "which point a dense temporal refinement stage applies the classifier "
        "at high temporal resolution across full recordings to produce "
        "frame-level probability traces and threshold-based bout annotations."
    ))
    _para(doc, (
        "Several design features distinguish ABEL from existing tools. "
        "First, the active-learning loop is tightly integrated with the "
        "GUI: candidate generation, clip extraction, and review are performed "
        "within a single interface, eliminating context-switching between "
        "tools. Second, temporal false-positive feedback allows researchers "
        "to flag misclassified intervals in a timeline view; these corrections "
        "are automatically incorporated into the next training round. Third, "
        "group-aware train\u2013validation splitting (by session or subject) "
        "prevents temporal and individual leakage, better approximating "
        "real-world generalization. Fourth, adaptive model complexity tuning "
        "scales regularization to the size of the positive training set, "
        "preventing overfitting in early active-learning rounds when labeled "
        "data are scarce. Fifth, mutual inhibition during temporal refinement "
        "penalizes frames where multiple behaviors score highly, reducing "
        "co-occurrence artifacts. Sixth, all artifacts are tagged with "
        "configuration hashes, model versions, and timestamps, supporting "
        "full computational reproducibility."
    ))
    _para(doc, (
        "ABEL is species- and behavior-agnostic and has been applied "
        "to mouse and rat recordings across fear-related (TMT predator-odor "
        "exposure, fear conditioning), locomotor (open field), anxiety-like "
        "(elevated plus maze), and home-cage paradigms. The tool is freely "
        "available, runs on standard computational hardware (with optional "
        "GPU acceleration for video feature extraction), and requires no "
        "programming. We describe the complete algorithmic pipeline, "
        "demonstrate performance across behavioral assays, and provide "
        "detailed technical documentation to facilitate adoption by "
        "behavioral neuroscience laboratories."
    ))

    path = os.path.join(OUT_DIR, "ABEL_Abstract_Introduction.docx")
    doc.save(path)
    print(f"Saved: {path}")


# =====================================================================
# DOCUMENT 3: Paper Checklist
# =====================================================================
def generate_paper_checklist():
    doc = Document()
    _setup_styles(doc)
    _add_title(doc, "ABEL Methods Paper: Content Checklist",
               "Elements Required to Satisfy Behavioral and Computational Neuroscience Reviewers")
    doc.add_paragraph()

    _para(doc, (
        "This document lists the sections, figures, tables, and supplementary "
        "materials that should be included in a standalone methods paper for "
        "ABEL. Items are organized by audience: those critical for "
        "behavioral neuroscientists (\u2b50), those critical for computational "
        "neuroscientists (\u2699), and those important for both (\u2605)."
    ))

    # ── Section 1: Manuscript sections ──
    doc.add_heading("1. Main Text Sections", level=1)

    doc.add_heading("1.1 Abstract (~250 words)", level=2)
    _bullet(doc, "Problem statement: manual annotation bottleneck in behavioral neuroscience.", "\u2605 ")
    _bullet(doc, "Core contribution: active-learning pipeline, closed-loop refinement, temporal bout extraction.", "\u2605 ")
    _bullet(doc, "Key results: species tested, paradigms demonstrated, performance metrics.", "\u2605 ")
    _bullet(doc, "Availability statement: open-source, GUI-driven, no programming required.", "\u2605 ")

    doc.add_heading("1.2 Introduction", level=2)
    _bullet(doc, "Motivation: why detailed behavioral phenotyping matters for circuit neuroscience.", "\u2b50 ")
    _bullet(doc, "Bottleneck: limitations of manual scoring (drift, subjectivity, temporal resolution).", "\u2b50 ")
    _bullet(doc, "Related work: position ABEL relative to SimBA, B-SOiD, MARS, JAABA, DeepEthogram, LabGym, BehaviorDEPOT (Table 1).", "\u2605 ")
    _bullet(doc, "Gap: no existing tool provides an integrated, GUI-driven active-learning loop from pose import to bout extraction.", "\u2605 ")
    _bullet(doc, "Contribution summary: 3\u20135 key innovations briefly listed.", "\u2699 ")

    doc.add_heading("1.3 Results", level=2)
    _bullet(doc, "Workflow overview with annotated screenshot or flowchart (Figure 1).", "\u2605 ")
    _bullet(doc, "Demonstrate the active-learning cycle: show how F1 / PR-AUC improves over successive labeling rounds (Figure 2).", "\u2605 ")
    _bullet(doc, "Cross-assay generalization: at least 2\u20133 distinct paradigms (e.g., TMT, open field, home cage). Report per-behavior precision, recall, F1, PR-AUC for each (Table 2).", "\u2b50 ")
    _bullet(doc, "Annotation efficiency: labeled frames vs. performance curve\u2014compare to SimBA's ~20 k-frame asymptote.", "\u2605 ")
    _bullet(doc, "Temporal refinement: example probability traces, bout Gantt charts, threshold sensitivity (Figure 3).", "\u2b50 ")
    _bullet(doc, "Group-aware splitting: demonstrate that subject- or session-level hold-out performance generalizes (Figure 4).", "\u2699 ")
    _bullet(doc, "Uncertainty-driven query selection: compare query strategies (uncertainty, novelty, random) on convergence rate (Figure 5).", "\u2699 ")
    _bullet(doc, "False-positive feedback: show that temporal feedback loop reduces type-I errors in subsequent rounds.", "\u2605 ")

    doc.add_heading("1.4 Discussion", level=2)
    _bullet(doc, "Active learning reduces annotation burden: quantify time savings relative to full-annotation approaches.", "\u2b50 ")
    _bullet(doc, "Limitations: DLC-only input; no unsupervised behavioral discovery; no SHAP/explainability (contrast with SimBA); no multi-animal tracking support.", "\u2605 ")
    _bullet(doc, "When NOT to use ABEL: behaviors without clear pose signatures (e.g., purely autonomic), raw-pixel approaches (DeepEthogram) may be preferable.", "\u2b50 ")
    _bullet(doc, "Relation to explainability: note that tree-based classifiers are inherently interpretable via feature importances; future integration of SHAP-like metrics is feasible.", "\u2699 ")
    _bullet(doc, "Scalability: discuss dataset sizes tested, hardware requirements, GPU vs. CPU trade-offs.", "\u2699 ")
    _bullet(doc, "Future directions: multi-format pose loader (SLEAP, maDLC), multi-animal social behavior, integration with neural data.", "\u2605 ")

    doc.add_heading("1.5 Methods (Detailed Technical Description)", level=2)
    _para(doc, (
        "The methods section should be comprehensive enough for independent "
        "reimplementation. Reference the Technical Documentation for full "
        "algorithmic detail. Include:"
    ))
    _bullet(doc, "Pose data cleaning pipeline (likelihood thresholding, interpolation, smoothing) with all default parameters.", "\u2699 ")
    _bullet(doc, "Kinematic feature extraction (nine-feature vector, sliding window params).", "\u2699 ")
    _bullet(doc, "Context feature extraction (optical flow, MOG2, spatial context) with algorithm parameters.", "\u2699 ")
    _bullet(doc, "Segment representation (z-scoring, 8-statistic aggregation, periodicity via FFT).", "\u2699 ")
    _bullet(doc, "Classifier training (XGBoost/LightGBM/HistGradient/RandomForest) with regularization settings.", "\u2699 ")
    _bullet(doc, "Probability calibration (sigmoid vs. isotonic).", "\u2699 ")
    _bullet(doc, "Uncertainty scoring (entropy, variance, density, margin; configurable weights).", "\u2699 ")
    _bullet(doc, "Candidate ranking and overlap suppression.", "\u2699 ")
    _bullet(doc, "Temporal refinement (dense sliding window, mutual inhibition, smoothing, bout extraction).", "\u2699 ")
    _bullet(doc, "Group-aware splitting (GroupShuffleSplit by session or subject).", "\u2699 ")
    _bullet(doc, "Evaluation metrics (frame-level, segment-level, bout-level).", "\u2605 ")
    _bullet(doc, "Experimental details for each demonstrated paradigm: species, strain, age, sex, arena, recording setup, DLC model (# keypoints, training images), video FPS and resolution.", "\u2b50 ")

    # ── Section 2: Figures ──
    doc.add_heading("2. Figures", level=1)
    figs = [
        ("Figure 1: ABEL Workflow",
         "Schematic pipeline diagram showing all stages from data import to export. "
         "Include annotated GUI screenshots alongside the flowchart. Show the "
         "iterative active-learning loop as a highlighted cycle.",
         "\u2605"),
        ("Figure 2: Active-Learning Convergence Curves",
         "Plot F1 (or PR-AUC) vs. number of labeled segments across successive "
         "active-learning rounds. Include multiple behaviors and/or paradigms. "
         "Overlay baselines: random query, full annotation.",
         "\u2605"),
        ("Figure 3: Temporal Refinement Example",
         "Per-frame probability traces for 1\u20132 behaviors over a full session. "
         "Show extracted bouts as shaded intervals. Include a Gantt-chart panel. "
         "Optionally overlay ground-truth annotations for validation.",
         "\u2b50"),
        ("Figure 4: Cross-Session and Cross-Subject Generalization",
         "Bar or violin plots of F1/precision/recall when session-held-out vs. "
         "subject-held-out vs. random split. Demonstrates leakage prevention.",
         "\u2699"),
        ("Figure 5: Query Strategy Comparison",
         "Learning curves under different candidate ranking strategies "
         "(uncertainty, novelty, low-probability, random). Shows that uncertainty "
         "sampling converges faster.",
         "\u2699"),
        ("Figure 6: Multi-Paradigm Demonstration",
         "Confusion matrices, PR curves, or example bout timelines for each "
         "tested paradigm (TMT, open field, EPM, home cage, fear conditioning). "
         "Include per-behavior performance.",
         "\u2b50"),
        ("Figure 7: Annotation Efficiency",
         "Compare minutes of positive annotated frames vs. classifier F1 for "
         "ABEL active learning vs. conventional full-video annotation. "
         "Reference SimBA's ~11 min / 20 k-frame result.",
         "\u2605"),
    ]
    for name, desc, audience in figs:
        p = doc.add_paragraph()
        r = p.add_run(f"{audience} {name}")
        r.bold = True
        _para(doc, desc)

    # ── Section 3: Tables ──
    doc.add_heading("3. Tables", level=1)
    tables = [
        ("Table 1: Comparison of Open-Source Behavioral Classification Tools",
         "Rows: SimBA, B-SOiD, A-SOiD, JAABA, MARS, DeepEthogram, LabGym, "
         "BehaviorDEPOT, ABEL. Columns: supervised/unsupervised, active "
         "learning, GUI, pose-estimation input, species demonstrated, "
         "explainability, temporal refinement, input format.",
         "\u2605"),
        ("Table 2: Per-Behavior Classification Performance",
         "Rows: each behavior \u00d7 paradigm. Columns: n_positive_segments, "
         "n_total_segments, precision, recall, F1, PR-AUC, split strategy.",
         "\u2605"),
        ("Table 3: Default Algorithm Parameters",
         "All parameters reported in the methods (likelihood threshold, "
         "interpolation gap, smoothing window, feature window/stride, "
         "XGBoost hyperparameters, calibration method, uncertainty weights, "
         "temporal stride, bout merge gap, minimum bout duration).",
         "\u2699"),
    ]
    for name, desc, audience in tables:
        p = doc.add_paragraph()
        r = p.add_run(f"{audience} {name}")
        r.bold = True
        _para(doc, desc)

    # ── Section 4: Supplementary ──
    doc.add_heading("4. Supplementary Materials", level=1)
    supp = [
        ("Supplementary Table S1: Feature List",
         "Complete enumeration of all kinematic and context features with "
         "descriptions, units, and which pipeline stage generates them.",
         "\u2699"),
        ("Supplementary Table S2: Behavior Operational Definitions",
         "Full text of each behavior's operational definition, inclusion "
         "and exclusion criteria, and minimum duration as used in "
         "demonstrated experiments.",
         "\u2b50"),
        ("Supplementary Figure S1: Pose Estimation Performance",
         "DLC model evaluation: per-keypoint pixel error, likelihood "
         "distributions, number of training images.",
         "\u2699"),
        ("Supplementary Figure S2: Feature Audit Heatmaps",
         "Variance and inter-feature correlation matrices for a representative "
         "dataset, showing the effect of feature exclusion.",
         "\u2699"),
        ("Supplementary Figure S3: Extended Performance Across Rounds",
         "Learning curves with confidence intervals for all tested behaviors "
         "and paradigms, with more detail than the main text figure.",
         "\u2605"),
        ("Supplementary Note S1: Software Installation and Quickstart",
         "Step-by-step instructions for installation, project creation, "
         "first import, and first active-learning round.",
         "\u2b50"),
        ("Supplementary Note S2: Mathematical Details",
         "Formal statements of uncertainty scoring, mutual inhibition, "
         "z-scoring, FFT periodicity computation, and calibration methods.",
         "\u2699"),
        ("Supplementary Video S1: Walkthrough",
         "Screen-recorded walkthrough of a complete ABEL session "
         "from import through export.",
         "\u2b50"),
    ]
    for name, desc, audience in supp:
        p = doc.add_paragraph()
        r = p.add_run(f"{audience} {name}")
        r.bold = True
        _para(doc, desc)

    # ── Section 5: Reviewer Expectations ──
    doc.add_heading("5. Anticipated Reviewer Expectations by Audience", level=1)

    doc.add_heading("5.1 Behavioral Neuroscientists Will Expect:", level=2)
    items_behav = [
        "Demonstration across multiple standard assays (at least 2\u20133 paradigms with distinct behavioral repertoires).",
        "Clear operational definitions for every classified behavior\u2014not just ML metrics.",
        "Comparison with manual scoring: inter-rater reliability (Cohen\u2019s \u03ba or Pearson R\u00b2) between ABEL output and expert human annotations on held-out videos.",
        "Bout-level biological plausibility: latency, frequency, duration distributions that match known literature.",
        "Practical usability: installation time, annotation time per behavior, time to first usable classifier.",
        "Reporting of sex, strain, age, housing, light cycle, and recording conditions for all animals.",
        "Discussion of when the tool fails or is inappropriate (e.g., behaviors without distinctive pose signatures).",
        "SimBA-style comparison: position your tool in the same table as SimBA, JAABA, B-SOiD, etc., so reviewers can quickly assess novelty.",
        "Acknowledgment that the tool is DLC-only and discussion of multi-format plans.",
    ]
    for item in items_behav:
        _bullet(doc, item)

    doc.add_heading("5.2 Computational Neuroscientists Will Expect:", level=2)
    items_comp = [
        "Formal definition of the active-learning loop as an algorithm (pseudocode or flowchart).",
        "Ablation studies: contribution of each uncertainty component (entropy, variance, density, margin) to annotation efficiency.",
        "Comparison of query strategies on convergence rate (uncertainty vs. random vs. novelty).",
        "Cross-validation methodology: explicit statement of GroupShuffleSplit preventing temporal leakage; comparison with na\u00efve random split.",
        "Calibration analysis: reliability diagrams showing that calibrated probabilities are well-calibrated.",
        "Hyperparameter sensitivity: effect of key parameters (likelihood threshold, feature window, uncertainty weights) on downstream F1.",
        "Computational cost analysis: wall-clock time per active-learning round, per session, on specified hardware.",
        "Reproducibility statement: pinned dependency versions, random seeds, configuration hashes.",
        "Discussion of feature engineering vs. representation learning: why hand-crafted features instead of learned embeddings (interpretability, data efficiency, computational cost).",
        "Scalability: how does performance / training time change with dataset size (# sessions, # frames)?",
        "Open discussion of limitations: no explainability metrics (SHAP), no unsupervised discovery, DLC-specific input format.",
    ]
    for item in items_comp:
        _bullet(doc, item)

    doc.add_heading("5.3 Both Audiences Will Expect:", level=2)
    items_both = [
        "Code and data availability statement with a persistent DOI (Zenodo, OSF, or GitHub release).",
        "Detailed software installation instructions (Supplementary Note).",
        "Complete list of parameters and their defaults (Table 3).",
        "Discussion of how the tool fits into the broader computational neuroethology ecosystem.",
        "Honest comparison with SimBA: what does ABEL do better (active learning, temporal feedback, uncertainty scoring) and what does SimBA do better (multi-species, SHAP explainability, community classifiers).",
        "A clear figure (Figure 1) that a non-computational reader can follow from data in to bout annotations out.",
        "Availability of example data and/or pre-trained classifiers for testing.",
    ]
    for item in items_both:
        _bullet(doc, item)

    # ── Section 6: Suggested Experiments ──
    doc.add_heading("6. Suggested Experiments to Include Before Submission", level=1)
    exps = [
        ("Human\u2013machine comparison",
         "Have 2\u20133 independent raters manually score 4\u20136 videos per paradigm. "
         "Compare ABEL bout annotations with human consensus "
         "(inter-rater reliability, Pearson R\u00b2, bout-level agreement)."),
        ("Active-learning efficiency experiment",
         "Starting from 3 seeds per behavior, plot F1 vs. # reviewed clips "
         "over 5\u20138 rounds. Compare to: (a) training on all manually scored data, "
         "(b) random-query baseline."),
        ("Query strategy ablation",
         "Run the same experiment with uncertainty, novelty, low-probability, "
         "and random strategies; compare convergence."),
        ("Cross-paradigm generalization",
         "Train on TMT data, test on open-field (or vice versa) for behaviors "
         "that overlap (e.g., freezing, locomotion). Report transfer F1."),
        ("Temporal refinement sensitivity",
         "Vary onset/offset thresholds, smoothing method, and mutual-inhibition "
         "weight; report effect on bout count and F1."),
        ("Calibration reliability",
         "Plot reliability diagrams (predicted probability vs. observed "
         "frequency) before and after calibration."),
    ]
    for name, desc in exps:
        p = doc.add_paragraph()
        r = p.add_run(name + ". ")
        r.bold = True
        p.add_run(desc)

    path = os.path.join(OUT_DIR, "ABEL_Paper_Checklist.docx")
    doc.save(path)
    print(f"Saved: {path}")


# ── Main ─────────────────────────────────────────────────────────────
if __name__ == "__main__":
    generate_methods_doc()
    generate_abstract_intro()
    generate_paper_checklist()
    print("\nAll three documents generated successfully.")
